### ISSUE TITLE
noqa after end of multi-line print statement

### ISSUE THREAD

**Issue by jayvdb** [JBKahn/flake8-print#10]
Currently it requires the `#noqa` on the same line as the print statement
```
print("foo"  # noqa
      " bar")
```

**Comment by JBKahn** [comment]
I'll take a look at this when I have some time, probably this coming weekend, I think I know why it's currently doing that, I'll see if I can tweak the code to work on the last line after the bracket.

**Comment by jayvdb** [comment]
Related flake8 plugins:
* https://github.com/openstack-dev/hacking/blob/master/hacking/checks/python23.py#L81 only handles print statements, and
* https://github.com/flowroute/ebb-lint#one-off-scripts has an unusual alternative to `noqa` and an extreme anti-`noqa` hack which cant be disabled (https://github.com/flowroute/ebb-lint/issues/7)

They would be worth documenting for people looking for slightly different linting outcomes.

**Comment by jayvdb** [comment]
I'm hoping to have this implemented in a codebase which will be participating in the Google Code-In, to reduce workload on reviewers.  GCI starts December 7.  Could this be released before then?

**Comment by JBKahn** [comment]
Oh right, forgot that I meant to release it. Tomorrow!

**Comment by JBKahn** [comment]
it's out.

**Comment by jayvdb** [comment]
much appreciated.
