### ISSUE TITLE
Doesn't install from setup.py

### ISSUE THREAD

**Issue by monokrome** [JBKahn/flake8-print#16]
Not sure if this is a supported usecase, but it looks like this library breaks when trying to install from a *setup.py* file.

**Comment by JBKahn** [comment]
Oh good catch, I've not tried that recently.

**Comment by jayvdb** [comment]
The `.travis.yml` does a `python setup.py install` to install this package.

Do you mean it doesnt work when `flake8-print` is included as a dependency in another package?

**Comment by monokrome** [comment]
@jayvdb If I create a barebones project and add `flake8-print` to the **requires** section, it doesn't install. Bails with an error, and even after using *pip install flake8-print* it doesn't show up in flake8

**Comment by JBKahn** [comment]
Interesting, I'm using the latest version over pip. What version of pip are
you using? What version of flake8? It installs fine and shows up on flake8
on my machine.

**Comment by JBKahn** [comment]
```bash

~ $ mkvirtualenv print-test
New python executable in print-test/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/joseph/.virtualenvs/print-test/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/joseph/.virtualenvs/print-test/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/joseph/.virtualenvs/print-test/bin/preactivate
virtualenvwrapper.user_scripts creating /home/joseph/.virtualenvs/print-test/bin/postactivate
virtualenvwrapper.user_scripts creating /home/joseph/.virtualenvs/print-test/bin/get_env_details

~ $ pip install flake8-print
Collecting flake8-print
  Using cached flake8_print-2.0.2-py2.py3-none-any.whl
Collecting flake8 (from flake8-print)
  Using cached flake8-2.5.4-py2.py3-none-any.whl
Collecting mccabe<0.5,>=0.2.1 (from flake8->flake8-print)
  Using cached mccabe-0.4.0-py2.py3-none-any.whl
Collecting pep8!=1.6.0,!=1.6.1,!=1.6.2,>=1.5.7 (from flake8->flake8-print)
  Using cached pep8-1.7.0-py2.py3-none-any.whl
Collecting pyflakes<1.1,>=0.8.1 (from flake8->flake8-print)
  Using cached pyflakes-1.0.0-py2.py3-none-any.whl
Installing collected packages: mccabe, pep8, pyflakes, flake8, flake8-print
Successfully installed flake8-2.5.4 flake8-print-2.0.2 mccabe-0.4.0 pep8-1.7.0 pyflakes-1.0.0
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

~ $ flake8 --version
2.5.4 (pep8: 1.7.0, flake8-print: 2.0.2, mccabe: 0.4.0, pyflakes: 1.0.0) CPython 2.7.6 on Linux

```

**Comment by JBKahn** [comment]
@monokrome could you provide the output of the failed install?

**Comment by hvelarde** [comment]
I'm having a similar problem installing with zc.buildout 1.7.1 and setuptools 0.6rc11:

https://travis-ci.org/collective/collective.fingerpointing/jobs/119268847

**Comment by JBKahn** [comment]
@hvelarde I've yet to reproduce it, could you modify the travis yaml file on a branch in that state and have it try to install the package in its own step so that I could get the output of the failed install. Presumable a `pip install flake8-print` would do.

**Comment by hvelarde** [comment]
`pip install flake8-print` does not fails as you can see here:

https://travis-ci.org/collective/collective.fingerpointing/jobs/119305388

nevertheless there is some sort of incompatibility as package is not downloading using zc.buildout; this was not happening before.

**Comment by JBKahn** [comment]
try it now

**Comment by hvelarde** [comment]
it's working now, thanks! what was? a missing file?

**Comment by JBKahn** [comment]
nah, extra file. I noticed I uploaded 3 files to pypi when I usually only upload one. must have put in a bad command

**Comment by hvelarde** [comment]
next time use [zest.releaser](https://pypi.python.org/pypi/zest.releaser) ;-)
