### ISSUE TITLE
Question: support for pprint detection

### ISSUE THREAD

**Issue by emilecaron** [JBKahn/flake8-print#21]
I usually use python `pprint` module when debugging.
Would it be nice to add another rule for this case? especially since it's not third-party but standard python.

Let me know if it seems useful, i'd be glad to submit a PR

**Comment by JBKahn** [comment]
sure, I'd be glad to add it in.

**Comment by emilecaron** [comment]
https://github.com/JBKahn/flake8-print/pull/22

**Comment by JBKahn** [comment]
released
