### ISSUE TITLE
specific # noqa exclusions are not supported

### ISSUE THREAD

**Issue by khomenko** [JBKahn/flake8-print#34]
If a specific error exclusion is specified in # noqa per http://flake8.pycqa.org/en/3.0.4/user/ignoring-errors.html#in-line-ignoring-errors, the plugin ignores the entire line. Should only ignore if flake8-print errors (T001-T004) are specified.

I took a quick look at pycodestyle.noqa, and it looks like it doesn't provide support for easily checking for specific codes unfortunately.

**Comment by JBKahn** [comment]
Nothing can be done as pycodestyle doesn't support that for extensions:
https://github.com/PyCQA/pycodestyle/blob/d219c684f117be77927d33146e76a5364161e518/pycodestyle.py#L2071)
