### ISSUE TITLE
Inline #nopep8 comment has no effect with 3.1.3

### ISSUE THREAD

**Issue by LKay** [JBKahn/flake8-print#41]
This might be related to #40 but violation is different, so I'm making new issue.

Our builds on CI server started to fail just when `3.1.3` was released. Seems like inline `# nopep8` comment has no effect anymore and on such line:
```
...
print(foo) # nopep8
...
```
results in violation error:
```
my_project/print_mailer.py:35:9: T001 print found.
```

It was just bump of patch part of semver so CI server fetched the most recent version and older version was present on my local machine. Took me a while to track down what was causing this, but everything seems to be working fine wit `3.1.1`.

**Comment by JBKahn** [comment]
This package never explicitly supported that as I have no idea that comment existed. So I'll take to take a look. There are no tests for that behavior.

**Comment by JBKahn** [comment]
Also, same as my reply to the other one. Can you give me a pip freeze or something to help me recreate the issue.

**Comment by JBKahn** [comment]
`3.1.4` released with support for that comment added.
