### ISSUE TITLE
Build to wheel

### ISSUE THREAD

**Issue by PeterJCLaw** [JBKahn/flake8-print#46]
It would be great if this project supported building to wheels as this would speed up installation for users and mean that they didn't need to run `setup.py`.

I'd be happy to put together a PR for this at some point if you'd be open to merging it.
Likely I'd base this on one of my existing projects which does build to wheels and introduce a script which wrapped the build and upload steps (with the help of the `twine` package).

**Comment by JBKahn** [comment]
Should be published with 4.0.0 now, let me know if that didn't work.
