### ISSUE TITLE
Allow `flake8` to handle `# noqa` comments

### ISSUE THREAD

**Issue by Zac-HD** [JBKahn/flake8-print#50]
This is a best practice, and also required for use with https://pypi.org/project/flake8-noqa/ - I think the implemenation is as simple as deleting these lines:

https://github.com/JBKahn/flake8-print/blob/539dd7697a40103d44b6a822992af8944f31896a/flake8_print.py#L105-L108

**Comment by JBKahn** [comment]
Merged that PR.
