### ISSUE TITLE
Chosen error code clashes with flake8-todos

### ISSUE THREAD

**Issue by ntaylorwss** [JBKahn/flake8-print#52]
See the issue I opened on flake8, which was promptly closed and redirected here: https://github.com/PyCQA/flake8/issues/1563

Comparing these two lines:

https://github.com/orsinium-labs/flake8-todos/blob/master/setup.py#L39
https://github.com/JBKahn/flake8-print/blob/master/pyproject.toml#L45

We see that `flake8-print` and `flake8-todos` are both attempting to reserve `T00` for their error codes. This prevents anyone from installing both plugins.

Could one of these tools please change their error code prefix? I would open this issue on `flake8-todos`, but it appears no one can open issues there.

**Comment by JBKahn** [comment]
I'll look at this for the next major release since it will require people to change their existing configs.

**Comment by JBKahn** [comment]
I pushed out 5.0.0 with the change. Hopefully this is fixed.
