### ISSUE TITLE
Publish on pypi

### ISSUE THREAD

**Issue by jayvdb** [JBKahn/flake8-print#9]
Could you publish this tool on pypi , so that it is easier to install.

**Comment by JBKahn** [comment]
Already on pypi:
https://pypi.python.org/pypi/flake8-print

**Comment by jayvdb** [comment]
Ah, interesting.  It doesnt appear in search

https://pypi.python.org/pypi?%3Aaction=search&term=flake8-print&submit=search

**Comment by JBKahn** [comment]
That is odd.
